
export const LEAD_ERROR = 'FETCH_LEAD_ERROR';
export const LEAD_REQUEST = 'FETCH_LEAD_REQUEST';
export const LEAD_SUCCESS = 'FETCH_LEAD_SUCCESS';

export const ONE_LEAD_ERROR = 'FETCH_ONE_LEAD_ERROR';
export const ONE_LEAD_REQUEST = 'FETCH_ONE_LEAD_REQUEST';
export const ONE_LEAD_SUCCESS = 'FETCH_ONE_LEAD_SUCCESS';

export const ADD_LEAD_ERROR = 'FETCH_ADD_LEAD_ERROR';
export const ADD_LEAD_REQUEST = 'FETCH_ADD_LEAD_REQUEST';
export const ADD_LEAD_SUCCESS = 'FETCH_ADD_LEAD_SUCCESS';

export const ADD_PERSON_ERROR = 'FETCH_ADD_PERSON_ERROR';
export const ADD_PERSON_REQUEST = 'FETCH_ADD_PERSON_REQUEST';
export const ADD_PERSON_SUCCESS = 'FETCH_ADD_PERSON_SUCCESS';

export const ADD_PHONE_ERROR = 'FETCH_ADD_PHONE_ERROR';
export const ADD_PHONE_REQUEST = 'FETCH_ADD_PHONE_REQUEST';
export const ADD_PHONE_SUCCESS = 'FETCH_ADD_PHONE_SUCCESS';

export const ADD_ADDRESS_ERROR = 'FETCH_ADD_ADDRESS_ERROR';
export const ADD_ADDRESS_REQUEST = 'FETCH_ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_SUCCESS = 'FETCH_ADD_ADDRESS_SUCCESS';

export const ADD_LEADDETAIL_ERROR = 'FETCH_ADD_LEADDEATIL_ERROR';
export const ADD_LEADDETAIL_REQUEST = 'FETCH_ADD_LEADDETAIL_REQUEST';
export const ADD_LEADDETAIL_SUCCESS = 'FETCH_ADD_LEADDETAIL_SUCCESS';

export const UPDATE_LEAD_ERROR = 'FETCH_UPDATE_LEAD_ERROR';
export const UPDATE_LEAD_REQUEST = 'FETCH_UPDATE_LEAD_REQUEST';
export const UPDATE_LEAD_SUCCESS = 'FETCH_UPDATE_LEAD_SUCCESS';

export const UPDATE_PERSON_ERROR = 'FETCH_UPDATE_PERSON_ERROR';
export const UPDATE_PERSON_REQUEST = 'FETCH_UPDATE_PERSON_REQUEST';
export const UPDATE_PERSON_SUCCESS = 'FETCH_UPDATE_PERSON_SUCCESS';

export const UPDATE_PHONE_ERROR = 'FETCH_UPDATE_PHONE_ERROR';
export const UPDATE_PHONE_REQUEST = 'FETCH_UPDATE_PHONE_REQUEST';
export const UPDATE_PHONE_SUCCESS = 'FETCH_UPDATE_PHONE_SUCCESS';

export const UPDATE_ADDRESS_ERROR = 'FETCH_UPDATE_ADDRESS_ERROR';
export const UPDATE_ADDRESS_REQUEST = 'FETCH_UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_SUCCESS = 'FETCH_UPDATE_ADDRESS_SUCCESS';

export const UPDATE_LEADDETAIL_ERROR = 'FETCH_UPDATE_LEADDEATIL_ERROR';
export const UPDATE_LEADDETAIL_REQUEST = 'FETCH_UPDATE_LEADDETAIL_REQUEST';
export const UPDATE_LEADDETAIL_SUCCESS = 'FETCH_UPDATE_LEADDETAIL_SUCCESS';

export const PROJECT_ERROR = 'FETCH_PROJECT_ERROR';
export const PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';

export const PROJECTDETAIL_ERROR = 'FETCH_PROJECTDEATIL_ERROR';
export const PROJECTDETAIL_REQUEST = 'FETCH_PROJECTDETAIL_REQUEST';
export const PROJECTDETAIL_SUCCESS = 'FETCH_PROJECTDETAIL_SUCCESS';

export const ADD_PROJECT_ERROR = 'FETCH_ADD_PROJECT_ERROR';
export const ADD_PROJECT_REQUEST = 'FETCH_ADD_PROJECT_REQUEST';
export const ADD_PROJECT_SUCCESS = 'FETCH_ADD_PROJECT_SUCCESS';

export const UPDATE_PROJECT_ERROR = 'FETCH_UPDATE_PROJECT_ERROR';
export const UPDATE_PROJECT_REQUEST = 'FETCH_UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'FETCH_UPDATE_PROJECT_SUCCESS';

export const ADD_PROJECTDETAIL_ERROR = 'FETCH_ADD_PROJECTDEATIL_ERROR';
export const ADD_PROJECTDETAIL_REQUEST = 'FETCH_ADD_PROJECTDETAIL_REQUEST';
export const ADD_PROJECTDETAIL_SUCCESS = 'FETCH_ADD_PROJECTDETAIL_SUCCESS';

export const UPDATE_PROJECTDETAIL_ERROR = 'FETCH_UPDATE_PROJECTDEATIL_ERROR';
export const UPDATE_PROJECTDETAIL_REQUEST = 'FETCH_UPDATE_PROJECTDETAIL_REQUEST';
export const UPDATE_PROJECTDETAIL_SUCCESS = 'FETCH_UPDATE_PROJECTDETAIL_SUCCESS';

export const LOGIN_ERROR = 'FETCH_LOGIN_ERROR';
export const LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';

export const CHANGEPASSWORD_ERROR = 'FETCH_CHANGEPASSWORD_ERROR';
export const CHANGEPASSWORD_REQUEST = 'FETCH_CHANGEPASSWORD_REQUEST';
export const CHANGEPASSWORD_SUCCESS = 'FETCH_CHANGEPASSWORD_SUCCESS';

export const LOGOUT_ERROR = 'FETCH_LOGOUT_ERROR';
export const LOGOUT_REQUEST = 'FETCH_LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';

export const FEEDBACK_ERROR = 'FETCH_FEEDBACK_ERROR';
export const FEEDBACK_REQUEST = 'FETCH_FEEDBACK_REQUEST';
export const FEEDBACK_SUCCESS = 'FETCH_FEEDBACK_SUCCESS';

export const PURCHASE_ERROR = 'FETCH_PURCHASE_ERROR';
export const PURCHASE_REQUEST = 'FETCH_PURCHASE_REQUEST';
export const PURCHASE_SUCCESS = 'FETCH_PURCHASE_SUCCESS';

export const CONTRACT_ERROR = 'FETCH_CONTRACT_ERROR';
export const CONTRACT_REQUEST = 'FETCH_CONTRACT_REQUEST';
export const CONTRACT_SUCCESS = 'FETCH_CONTRACT_SUCCESS';

export const ADD_CONTRACT_ERROR = 'FETCH_ADD_CONTRACT_ERROR';
export const ADD_CONTRACT_REQUEST = 'FETCH_ADD_CONTRACT_REQUEST';
export const ADD_CONTRACT_SUCCESS = 'FETCH_ADD_CONTRACT_SUCCESS';

export const SYSTEM_ERROR = 'FETCH_SYSTEM_ERROR';
export const SYSTEM_REQUEST = 'FETCH_SYSTEM_REQUEST';
export const SYSTEM_SUCCESS = 'FETCH_SYSTEM_SUCCESS';

export const ONE_SYSTEM_ERROR = 'FETCH_ONE_SYSTEM_ERROR';
export const ONE_SYSTEM_REQUEST = 'FETCH_ONE_SYSTEM_REQUEST';
export const ONE_SYSTEM_SUCCESS = 'FETCH_ONE_SYSTEM_SUCCESS';

export const ADD_SYSTEM_ERROR = 'FETCH_ADD_SYSTEM_ERROR';
export const ADD_SYSTEM_REQUEST = 'FETCH_ADD_SYSTEM_REQUEST';
export const ADD_SYSTEM_SUCCESS = 'FETCH_ADD_SYSTEM_SUCCESS';

export const UPDATE_SYSTEM_ERROR = 'FETCH_UPDATE_SYSTEM_ERROR';
export const UPDATE_SYSTEM_REQUEST = 'FETCH_UPDATE_SYSTEM_REQUEST';
export const UPDATE_SYSTEM_SUCCESS = 'FETCH_UPDATE_SYSTEM_SUCCESS';

export const COLOR_ERROR = 'FETCH_COLOR_ERROR';
export const COLOR_REQUEST = 'FETCH_COLOR_REQUEST';
export const COLOR_SUCCESS = 'FETCH_COLOR_SUCCESS';

export const ADD_COLOR_ERROR = 'FETCH_ADD_COLOR_ERROR';
export const ADD_COLOR_REQUEST = 'FETCH_ADD_COLOR_REQUEST';
export const ADD_COLOR_SUCCESS = 'FETCH_ADD_COLOR_SUCCESS';

export const UPDATE_COLOR_ERROR = 'FETCH_UPDATE_COLOR_ERROR';
export const UPDATE_COLOR_REQUEST = 'FETCH_UPDATE_COLOR_REQUEST';
export const UPDATE_COLOR_SUCCESS = 'FETCH_UPDATE_COLOR_SUCCESS';

export const DELETE_COLOR_ERROR = 'FETCH_DELETE_COLOR_ERROR';
export const DELETE_COLOR_REQUEST = 'FETCH_DELETE_COLOR_REQUEST';
export const DELETE_COLOR_SUCCESS = 'FETCH_DELETE_COLOR_SUCCESS';

export const INGREDIENT_ERROR = 'FETCH_INGREDIENT_ERROR';
export const INGREDIENT_REQUEST = 'FETCH_INGREDIENT_REQUEST';
export const INGREDIENT_SUCCESS = 'FETCH_INGREDIENT_SUCCESS';

export const ONE_INGREDIENT_ERROR = 'FETCH_ONE_INGREDIENT_ERROR';
export const ONE_INGREDIENT_REQUEST = 'FETCH_ONE_INGREDIENT_REQUEST';
export const ONE_INGREDIENT_SUCCESS = 'FETCH_ONE_INGREDIENT_SUCCESS';

export const ADD_INGREDIENT_ERROR = 'FETCH_ADD_INGREDIENT_ERROR';
export const ADD_INGREDIENT_REQUEST = 'FETCH_ADD_INGREDIENT_REQUEST';
export const ADD_INGREDIENT_SUCCESS = 'FETCH_ADD_INGREDIENT_SUCCESS';

export const UPDATE_INGREDIENT_ERROR = 'FETCH_UPDATE_INGREDIENT_ERROR';
export const UPDATE_INGREDIENT_REQUEST = 'FETCH_UPDATE_INGREDIENT_REQUEST';
export const UPDATE_INGREDIENT_SUCCESS = 'FETCH_UPDATE_INGREDIENT_SUCCESS';

export const PATTERN_ERROR = 'FETCH_PATTERN_ERROR';
export const PATTERN_REQUEST = 'FETCH_PATTERN_REQUEST';
export const PATTERN_SUCCESS = 'FETCH_PATTERN_SUCCESS';

export const ADD_PATTERN_ERROR = 'FETCH_ADD_PATTERN_ERROR';
export const ADD_PATTERN_REQUEST = 'FETCH_ADD_PATTERN_REQUEST';
export const ADD_PATTERN_SUCCESS = 'FETCH_ADD_PATTERN_SUCCESS';

export const UPDATE_PATTERN_ERROR = 'FETCH_UPDATE_PATTERN_ERROR';
export const UPDATE_PATTERN_REQUEST = 'FETCH_UPDATE_PATTERN_REQUEST';
export const UPDATE_PATTERN_SUCCESS = 'FETCH_UPDATE_PATTERN_SUCCESS';

export const UPLOADIMAGE_ERROR = 'FETCH_UPLOADIMAGE_ERROR';
export const UPLOADIMAGE_REQUEST = 'FETCH_UPLOADIMAGE_REQUEST';
export const UPLOADIMAGE_SUCCESS = 'FETCH_UPLOADIMAGE_SUCCESS';

export const GET_IMAGE_ERROR = 'FETCH_IMAGE_ERROR';
export const GET_IMAGE_REQUEST = 'FETCH_IMAGE_REQUEST';
export const GET_IMAGE_SUCCESS = 'FETCH_IMAGE_SUCCESS';

export const NOTE_ERROR = 'FETCH_NOTE_ERROR';
export const NOTE_REQUEST = 'FETCH_NOTE_REQUEST';
export const NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';

export const ADD_NOTE_ERROR = 'FETCH_ADD_NOTE_ERROR';
export const ADD_NOTE_REQUEST = 'FETCH_ADD_NOTE_REQUEST';
export const ADD_NOTE_SUCCESS = 'FETCH_ADD_NOTE_SUCCESS';

export const UPDATE_NOTE_ERROR = 'FETCH_UPDATE_NOTE_ERROR';
export const UPDATE_NOTE_REQUEST = 'FETCH_UPDATE_NOTE_REQUEST';
export const UPDATE_NOTE_SUCCESS = 'FETCH_UPDATE_NOTE_SUCCESS';

export const STATE_ERROR = 'FETCH_STATE_ERROR';
export const STATE_REQUEST = 'FETCH_STATE_REQUEST';
export const STATE_SUCCESS = 'FETCH_STATE_SUCCESS';
